name: testCompose

networks:
 first:
  driver: bridge
 second:
  driver: bridge
 

services:
 first:
  image: alpine:latest
  command: ["top"]
  networks:
  - second

 database:
  image: postgres:latest
  environment:
   - POSTGRES_PASSWORD=pass
   - POSTGRES_USER=postgres
  ports:
   - "5432:5432"
  networks:
   - first

 web:
  image: web-hocorend
  build: 
   context: .
   dockerfile: prod.Dockerfile
  ports:
   - "8082:8080"
  environment:
   - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/postgres
  networks:
   - first
   - second
